server:
  port: 8080
  servlet:
    context-path: /api



spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3303/chuong_trinh_dao_tao"
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true